### ISSUE TITLE
Some keywords not highlighted

### ISSUE THREAD

**Issue by oehme** [xtext/xtext-website#3]
Highlighting is missing e.g. for 'grammar' and 'generate'
![highlighting](https://cloud.githubusercontent.com/assets/1191797/6289175/71cfcfa4-b91e-11e4-82a5-f867fb61286d.PNG)

**Comment by oehme** [comment]
Same goes for the example languages

![highlighting](https://cloud.githubusercontent.com/assets/1191797/6289200/a65a5a82-b91e-11e4-9d0e-fd91d4223855.PNG)

**Comment by svenefftinge** [comment]
fixed
